# Form implementation generated from reading ui file './ui_batchInference.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from ml.prediction_batch import predict_from_csv
import pandas as pd


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        
        # form layout
        self.form_layout = QtWidgets.QVBoxLayout(Form)
        self.form_layout.setObjectName("form_layout")

        # add top spacer
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.form_layout.addItem(spacerItem)

        # card container
        self.container = QtWidgets.QWidget(parent=Form)
        self.container.setObjectName("container")
        self.container_layout = QtWidgets.QHBoxLayout(self.container)
        self.container_layout.setObjectName("container_layout")

        # add left spacer
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.container_layout.addItem(spacerItem1)

        # card widget
        self.card = QtWidgets.QWidget(parent=self.container)
        self.card.setObjectName("card")
        self.card_layout = QtWidgets.QVBoxLayout(self.card)
        self.card_layout.setObjectName("card_layout")

        # title label
        self.label = QtWidgets.QLabel(parent=self.card)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.card_layout.addWidget(self.label)

        # file input
        self.widget = QtWidgets.QWidget(parent=self.card)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        # display file path
        self.file_path = QtWidgets.QLineEdit(parent=self.widget)
        self.file_path.setReadOnly(True)
        self.file_path.setObjectName("file_path")
        self.horizontalLayout.addWidget(self.file_path)
        self.browse_button = QtWidgets.QPushButton(parent=self.widget)
        self.browse_button.clicked.connect(self.browse_file)
        self.browse_button.setObjectName("browse_button")
        self.horizontalLayout.addWidget(self.browse_button)
        self.card_layout.addWidget(self.widget)

        # message to ask user to select file
        self.label_2 = QtWidgets.QLabel(parent=self.card)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.card_layout.addWidget(self.label_2)

        # error display label
        self.label_3 = QtWidgets.QLabel(parent=self.card)
        # default to hidden
        self.label_3.setVisible(False)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.card_layout.addWidget(self.label_3)

        # predict button
        self.button_predict = QtWidgets.QPushButton(parent=self.card)
        self.button_predict.setObjectName("button_predict")
        self.card_layout.addWidget(self.button_predict)
        self.container_layout.addWidget(self.card)

        # add right spacer
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.container_layout.addItem(spacerItem2)

        # add container to form layout
        self.form_layout.addWidget(self.container)

        # add bottom spacer
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.form_layout.addItem(spacerItem3)

        shadow = QtWidgets.QGraphicsDropShadowEffect(blurRadius=18, xOffset=0, yOffset=6)
        shadow.setColor(QtGui.QColor(0,0,0,35))
        self.card.setGraphicsEffect(shadow)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Batch Prediction"))
        self.browse_button.setText(_translate("Form", "Select a file"))
        self.label_2.setText(_translate("Form", "Please select a file to perform batch prediction"))
        self.label_3.setText(_translate("Form", "Show error here if something happens"))
        self.button_predict.setText(_translate("Form", "Predict"))

    def browse_file(self):
        self.label_3.setVisible(False)  # hide error label on new browse

        filename, _ = QtWidgets.QFileDialog.getOpenFileName(
            self,
            "Select CSV file",
            "",
            "CSV Files (*.csv);;All Files (*)"
        )
        if not filename:
            return

        self.file_path.setText(filename)

    def predict_button_clicked(self):
        filename = self.file_path.text()
        # Basic validation/read
        try:
            df = pd.read_csv(filename)
        except Exception as e:
            self.label_3.setText(f"Failed to read CSV:\n{e}")
            self.label_3.setVisible(True)
            return
        # Optional: minimal column check before calling predict function
        required_cols = {"ID", "Gene", "Variation", "Text"}
        if not required_cols.issubset(df.columns):
            self.label_3.setText(f"CSV must contain columns: {required_cols}")
            self.label_3.setVisible(True)
            return
        
        try:
            
            result = predict_from_csv(filename, pipeline_path="ml/pipeline.joblib", out_csv="predictions_batch.csv")
        except Exception as e:
            self.label_3.setText(f"Prediction failed:\n{e}")
            self.label_3.setVisible(True)
            return
        # If you want to inspect result dict and show top prediction:
        top = result["result"]["predicted_class"][0]
        QtWidgets.QMessageBox.information(self, "Top result", f"Top predicted class for first row: {top}")


class BatchInferenceWidget(QtWidgets.QWidget, Ui_Form):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.parent = parent
        self.setObjectName("batch_inference_container")
        # setupUi expects a widget; provide self so this object becomes the UI widget
        self.setAttribute(QtCore.Qt.WidgetAttribute.WA_StyledBackground, True)
        self.setupUi(self)

        self.apply_styles()

        self.button_predict.clicked.connect(self.predict)

    def predict(self):

        #============== FILE READING & PREDICTION ==============
        filename = self.file_path.text()
        # Basic validation/read
        try:
            df = pd.read_csv(filename)
        except Exception as e:
            self.label_3.setText(f"Failed to read CSV:\n{e}")
            self.label_3.setVisible(True)
            return
        # Optional: minimal column check before calling predict function
        required_cols = {"ID", "Gene", "Variation", "Text"}
        if not required_cols.issubset(df.columns):
            self.label_3.setText(f"CSV must contain columns: {required_cols}")
            self.label_3.setVisible(True)
            return
        
        try:
            result = predict_from_csv(filename, pipeline_path="ml/pipeline.joblib", out_csv="predictions_batch.csv")
        except Exception as e:
            self.label_3.setText(f"Prediction failed:\n{e}")
            self.label_3.setVisible(True)
            return
        #===========================================================

        self.main_display = self.parent
        self.main_display_layout = self.main_display.layout()
        layout = self.main_display_layout
        while layout.count():
            item = layout.takeAt(0)
            w = item.widget()
            if w is not None:
                w.setParent(None)
                w.deleteLater()
        
        from ui.result_batch_ui import ResultBatchWidget
        self.result_window = ResultBatchWidget(parent=self.main_display)
        self.tableWidget = self.result_window.tableWidget
        # populate the table
        self.result_window.populate_table_from_results(df, result, **{"status_label": self.label_3})

        # # setup combo box for ID selection
        # self.combo_box = self.result_window.comboBox
        # # the list of serial numbers is the value for the combo box
        # combo_box_values = df["ID"].tolist()
        # self.combo_box.setMinimumWidth(200)
        # self.combo_box.setCurrentText(str(combo_box_values[0]))
        # # limit visible items in the dropdown
        # self.combo_box.setMaxVisibleItems(10)  # or whatever number you prefer
        # # enforce via stylesheet if you notice the list is still too tall
        # self.combo_box.setStyleSheet("QComboBox { combobox-popup: 0; }")
        # self.combo_box.addItems([str(v) for v in combo_box_values])

        

        self.main_display_layout.addWidget(self.result_window)
    
    def apply_styles(self):
            self.setStyleSheet("""
        /* --- Global --- */
        QWidget {
            font-family: "Segoe UI", "Inter", "Arial", sans-serif;
            font-size: 13px;
            color: #0f172a; /* slate-900 */
        }

        /* Top-level container background (the page area) */
        QWidget#batch_inference_container {
            background-color: #f1f5f9; /* very light slate */
            padding-top: 24px;
            padding-bottom: 24px;
        }

        /* Outer container that centers the card horizontally */
        QWidget#container {
            background: transparent;
        }

        /* The card */
        QWidget#card {
            background-color: #ffffff;
            border-radius: 12px;
            border: 1px solid #e6eef6; /* subtle blue-tinged border */
            padding: 28px 34px;
            /* Consider adding a QGraphicsDropShadowEffect in code for a natural shadow */
        }

        /* Title */
        QLabel#label {
            font-size: 16px;
            font-weight: 700;
            color: #0f172a;
            margin-bottom: 12px;
        }

        /* Secondary text / helper text */
        QLabel#label_2, QLabel#label_3 {
            font-size: 13px;
            font-weight: 500;
            color: #475569; /* slate-600 for readable muted text */
        }
        QLabel#label_3 {
            margin-top: 8px;
            color: #6b7280; /* slightly lighter for the error/info line */
        }

        /* File path input */
        QLineEdit#file_path {
            background-color: #ffffff;
            border: 1px solid #dbe6f2;
            border-radius: 8px;
            padding: 8px 10px;
            min-width: 360px;
            min-height: 30px;
        }
        QLineEdit#file_path:focus {
            border: 1px solid #2563eb; /* primary blue on focus */
            outline: none;
        }
        QLineEdit#file_path::placeholder {
            color: #9ca3af;
        }
        QLineEdit[readOnly="true"] {
            background-color: #f8fafc;
        }

        /* Browse button — subtle, neutral */
        QPushButton#browse_button {
            background-color: transparent;
            border: 1px solid #cbd5e1;
            border-radius: 8px;
            padding: 8px 12px;
            font-weight: 600;
            color: #0f172a;
            min-height: 32px;
        }
        QPushButton#browse_button:hover {
            background-color: #f1f5f9;
            border-color: #a3bede;
        }

        /* Primary action (Predict) — prominent */
        QPushButton#button_predict {
            background-color: #2563eb;
            color: #ffffff;
            border-radius: 8px;
            padding: 10px 20px;
            font-size: 14px;
            font-weight: 800;
            min-width: 140px;
            min-height: 36px;
        }
        QPushButton#button_predict:hover {
            background-color: #1d4ed8;
        }
        QPushButton#button_predict:pressed {
            background-color: #153e9b;
        }
        QPushButton#button_predict:disabled {
            background-color: #bfe0ff;
            color: #ffffff;
            opacity: 0.9;
        }

        /* Layout niceties: ensure the file row items align and have breathing room */
        QWidget#widget, QWidget#file_select_widget {
            margin-top: 6px;
            margin-bottom: 6px;
        }

        /* Make small adjustments for very narrow widths */
        @media (max-width: 480px) {
            QLineEdit#file_path { min-width: 200px; }
            QWidget#card { padding: 20px; }
        }
        """)

    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    # instantiate the wrapper widget (can be added to any layout)
    widget = BatchInferenceWidget()
    widget.show()
    sys.exit(app.exec())

