# Form implementation generated from reading ui file './ui_history.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from db_manager.db_utils import read_table


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(658, 558)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(parent=self.widget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.setMinimumWidth(200)
        # limit visible items in the dropdown
        self.comboBox.setMaxVisibleItems(10)  # or whatever number you prefer
        # # enforce via stylesheet if you notice the list is still too tall
        self.comboBox.setStyleSheet("QComboBox { combobox-popup: 0; }")
        self.horizontalLayout.addWidget(self.comboBox)
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(465, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.widget)
        self.line = QtWidgets.QFrame(parent=Form)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.tableWidget = QtWidgets.QTableWidget(parent=Form)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "View"))


# --- Minimal wrapper so the UI can be used as a QWidget ---
class HistoryFormWidget(QtWidgets.QWidget, Ui_Form):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.parent = parent
        # setupUi expects a widget; provide self so this object becomes the UI widget
        self.setupUi(self)
        self.apply_styles()

        data = read_table("db_manager/database/history", "history_table")
        # data is a dict-of-lists: ["col 1": [col 1 values...], "col 2": [col 2 values...], ...]
        columns = ["Serial Number", "Name", "Saved on", "Single/Batch"]
        self.populate_table(columns, list(data.values()))
        self.pushButton.clicked.connect(self.on_view_button_clicked)

    def populate_table(self, columns, data):
        """
        Populate the table with given columns and data.
        :param columns: List of column names.
        :param data: a list-of-lists: [[col 1 values...], [col 2 values...], ...]
        """
        self.tableWidget.clear()
        self.tableWidget.setColumnCount(len(columns))
        self.tableWidget.setRowCount(len(data[0]) + 1)
        self.tableWidget.setHorizontalHeaderLabels(columns)

        for col_idx, column in enumerate(columns):
            self.tableWidget.setColumnWidth(col_idx, 200)

        serial_numbers = [str(i + 1) for i in range(len(data[0]))]
        for row_idx, serial_number in enumerate(serial_numbers):
            item = QtWidgets.QTableWidgetItem(serial_number)
            self.tableWidget.setItem(row_idx, 0, item)
        names = data[0]
        for row_idx, name in enumerate(names):
            item = QtWidgets.QTableWidgetItem(name)
            self.tableWidget.setItem(row_idx, 1, item)
        saved_ons = data[1]
        for row_idx, saved_on in enumerate(saved_ons):
            item = QtWidgets.QTableWidgetItem(saved_on)
            self.tableWidget.setItem(row_idx, 2, item)
        types = data[2]
        for row_idx, type_ in enumerate(types):
            item = QtWidgets.QTableWidgetItem(type_)
            self.tableWidget.setItem(row_idx, 3, item)

        # also update the combo box values with serial number
        self.comboBox.clear()
        combo_box_values = serial_numbers
        self.comboBox.addItems(combo_box_values)

    def on_view_button_clicked(self):
        """
        Handle the View button click event.
        """
        selected_index = int(self.comboBox.currentIndex())
        # get the table values in that row
        value_list = []
        for col in range(self.tableWidget.columnCount()):
            item = self.tableWidget.item(selected_index, col).text()
            value_list.append(item if item else "")

        name = value_list[1]
        type_ = value_list[3]
        
        if type_ == "Single":
            from ui.result_single_ui import ResultSingleWidget
            from db_manager.db_utils import get_a_row
            data = get_a_row("db_manager/database/single_inference", "single_inference_table", "Name", name)
            gene = data['Gene']
            variation = data['Variation']
            text = data['Text']
            predicted_class = data['Predicted_Class']
            class1_prob = data['Class_1_probability']
            class2_prob = data['Class_2_probability']
            class3_prob = data['Class_3_probability']
            class4_prob = data['Class_4_probability']
            class5_prob = data['Class_5_probability']
            class6_prob = data['Class_6_probability']
            class7_prob = data['Class_7_probability']
            class8_prob = data['Class_8_probability']
            class9_prob = data['Class_9_probability']
            dict_to_pass = {
            "gene": gene,
            "variation": variation,
            "text": text,
            "predicted_class": predicted_class,
            "class1_prob": class1_prob,
            "class2_prob": class2_prob,
            "class3_prob": class3_prob,
            "class4_prob": class4_prob,
            "class5_prob": class5_prob,
            "class6_prob": class6_prob,
            "class7_prob": class7_prob,
            "class8_prob": class8_prob,
            "class9_prob": class9_prob,
        }
            result_widget = ResultSingleWidget(parent=self.parent)
            result_widget.populate_data(**dict_to_pass)
            
        else:  # Batch
            from ui.result_batch_ui import ResultBatchWidget
            from ui.batch_view_data_splitter import split_data_for_table
            result_widget = ResultBatchWidget(parent=self.parent)
            data = read_table("db_manager/database/batch_inference", name)
            input_df, result = split_data_for_table(data)
            result_widget.populate_table_from_results(input_df, result)

        # disable back and save buttons
        result_widget.toolButton.setEnabled(False)
        result_widget.toolButton_2.setEnabled(False)

        self.main_display = self.parent
        self.main_display_layout = self.main_display.layout()
        layout = self.main_display_layout
        while layout.count():
            item = layout.takeAt(0)
            w = item.widget()
            if w is not None:
                w.setParent(None)
                w.deleteLater()

        self.main_display_layout.addWidget(result_widget)

    def apply_styles(self):
        """
        Call this after setupUi(self).
        """
        self.setStyleSheet("""
    /* ---------- GLOBAL ---------- */
    QWidget {
        font-family: "Segoe UI", "Inter", "Arial", sans-serif;
        font-size: 13px;
        color: #0f172a;              /* slate-900 */
        background: transparent;
    }

    /* ---------- TOOLBAR (top) ---------- */
    

    /* ComboBox - slim, modern */
    QComboBox#comboBox {
        background-color: #ffffff;
        border: 1px solid #cbd5e1;
        border-radius: 8px;
        padding: 6px 10px;
        min-width: 80px;
        min-height: 20px;
    }
    QComboBox#comboBox::drop-down {
        subcontrol-origin: padding;
        subcontrol-position: top right;
        width: 28px;
        border-left: 1px solid #e6eef6;
    }
    QComboBox#comboBox QAbstractItemView {
        background-color: #ffffff;
        border: 1px solid #e6eef6;
        selection-background-color: #e6f0ff;
    }

    /* Primary action button */
    QPushButton#pushButton {
        background-color: #2563eb;
        color: #ffffff;
        border-radius: 8px;
        padding: 8px 14px;
        font-weight: 700;
        min-height: 20px;
    }
    QPushButton#pushButton:hover {
        background-color: #1d4ed8;
    }
    QPushButton#pushButton:pressed {
        background-color: #153e9b;
    }
    QPushButton#pushButton:disabled {
        background-color: #bfe0ff;
        color: #ffffff;
    }

    /* ---------- SEPARATOR LINE ---------- */
    QFrame#line {
        background: transparent;
        border: none;
        min-height: 1px;
        margin: 6px 0;
    }

    /* ---------- TABLE (card-like) ---------- */
    QTableWidget#tableWidget {
        background-color: #ffffff;
        border: 1px solid #e6eef6;
        border-radius: 12px;
        padding: 8px;                /* not visually applied to table cells but keeps consistency */
        gridline-color: #f1f5f9;
        selection-background-color: #e6f0ff;
        selection-color: #0f172a;
    }

    /* alternate rows */
    QTableView {
        alternate-background-color: #fbfdff;
    }

    /* Header */
    QHeaderView::section {
        background-color: #f8fafc;
        color: #334155;
        padding: 8px 10px;
        border: 0;
        border-bottom: 1px solid #e6eef6;
        font-weight: 700;
        font-size: 13px;
    }

    /* Remove focus rectangle from the table */
    QTableWidget:focus {
        outline: none;
    }

    /* Cell content */
    QTableWidget::item {
        padding: 8px;
        border-bottom: 1px solid rgba(226,232,240,0.6);
    }

    /* Horizontal header resize handle (small affordance) */
    QHeaderView::section:horizontal:hover {
        background-color: #f1f5f9;
    }

    /* Empty-state / placeholder rows use muted color */
    QTableWidget QLabel, QTableWidget QLineEdit {
        color: #64748b;
    }

    /* Scrollbars — thin & subtle */
    QScrollBar:vertical {
        width: 10px;
        background: transparent;
        margin: 6px 0 6px 0;
    }
    QScrollBar::handle:vertical {
        min-height: 20px;
        border-radius: 5px;
        background: #cbd5e1;
    }
    QScrollBar::handle:vertical:hover { background: #a3bede; }
    QScrollBar::add-line, QScrollBar::sub-line { height: 0; }

    """)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    # instantiate the wrapper widget (can be added to any layout)
    widget = HistoryFormWidget()
    widget.show()
    sys.exit(app.exec())

