# Form implementation generated from reading ui file './ui_history.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(658, 558)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(parent=self.widget)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(465, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.widget)
        self.line = QtWidgets.QFrame(parent=Form)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.tableWidget = QtWidgets.QTableWidget(parent=Form)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "View"))


# --- Minimal wrapper so the UI can be used as a QWidget ---
class HistoryFormWidget(QtWidgets.QWidget, Ui_Form):
    def __init__(self, parent=None):
        super().__init__(parent)
        # setupUi expects a widget; provide self so this object becomes the UI widget
        self.setupUi(self)
        self.apply_styles()

    def apply_styles(self):
        """
        Call this after setupUi(self).
        """
        self.setStyleSheet("""
    /* ---------- GLOBAL ---------- */
    QWidget {
        font-family: "Segoe UI", "Inter", "Arial", sans-serif;
        font-size: 13px;
        color: #0f172a;              /* slate-900 */
        background: transparent;
    }

    /* ---------- TOOLBAR (top) ---------- */
    

    /* ComboBox - slim, modern */
    QComboBox#comboBox {
        background-color: #ffffff;
        border: 1px solid #cbd5e1;
        border-radius: 8px;
        padding: 6px 10px;
        min-width: 80px;
        min-height: 20px;
    }
    QComboBox#comboBox::drop-down {
        subcontrol-origin: padding;
        subcontrol-position: top right;
        width: 28px;
        border-left: 1px solid #e6eef6;
    }
    QComboBox#comboBox QAbstractItemView {
        background-color: #ffffff;
        border: 1px solid #e6eef6;
        selection-background-color: #e6f0ff;
    }

    /* Primary action button */
    QPushButton#pushButton {
        background-color: #2563eb;
        color: #ffffff;
        border-radius: 8px;
        padding: 8px 14px;
        font-weight: 700;
        min-height: 20px;
    }
    QPushButton#pushButton:hover {
        background-color: #1d4ed8;
    }
    QPushButton#pushButton:pressed {
        background-color: #153e9b;
    }
    QPushButton#pushButton:disabled {
        background-color: #bfe0ff;
        color: #ffffff;
    }

    /* ---------- SEPARATOR LINE ---------- */
    QFrame#line {
        background: transparent;
        border: none;
        min-height: 1px;
        margin: 6px 0;
    }

    /* ---------- TABLE (card-like) ---------- */
    QTableWidget#tableWidget {
        background-color: #ffffff;
        border: 1px solid #e6eef6;
        border-radius: 12px;
        padding: 8px;                /* not visually applied to table cells but keeps consistency */
        gridline-color: #f1f5f9;
        selection-background-color: #e6f0ff;
        selection-color: #0f172a;
    }

    /* alternate rows */
    QTableView {
        alternate-background-color: #fbfdff;
    }

    /* Header */
    QHeaderView::section {
        background-color: #f8fafc;
        color: #334155;
        padding: 8px 10px;
        border: 0;
        border-bottom: 1px solid #e6eef6;
        font-weight: 700;
        font-size: 13px;
    }

    /* Remove focus rectangle from the table */
    QTableWidget:focus {
        outline: none;
    }

    /* Cell content */
    QTableWidget::item {
        padding: 8px;
        border-bottom: 1px solid rgba(226,232,240,0.6);
    }

    /* Horizontal header resize handle (small affordance) */
    QHeaderView::section:horizontal:hover {
        background-color: #f1f5f9;
    }

    /* Empty-state / placeholder rows use muted color */
    QTableWidget QLabel, QTableWidget QLineEdit {
        color: #64748b;
    }

    /* Scrollbars — thin & subtle */
    QScrollBar:vertical {
        width: 10px;
        background: transparent;
        margin: 6px 0 6px 0;
    }
    QScrollBar::handle:vertical {
        min-height: 20px;
        border-radius: 5px;
        background: #cbd5e1;
    }
    QScrollBar::handle:vertical:hover { background: #a3bede; }
    QScrollBar::add-line, QScrollBar::sub-line { height: 0; }

    """)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    # instantiate the wrapper widget (can be added to any layout)
    widget = HistoryFormWidget()
    widget.show()
    sys.exit(app.exec())

